## 1 Разработка модели машинного обучения

### 1. Обучающая выборка данных разделена на обучающую и тестовую выборку

In [71]:
import pandas as pd
import pandas as pd
from sklearn.model_selection import train_test_split

In [85]:
data_y_val = pd.read_csv('data_y_val.csv', skiprows=lambda x: x % 500 != 0)
data_y_val.reset_index(drop=True, inplace=True)
data_X_val = pd.read_csv('data_X_val.csv', skiprows=lambda x: x % 500 != 0)
data_X_val.reset_index(drop=True, inplace=True)
data_y = pd.read_csv('data_y.csv', skiprows=lambda x: x % 500 != 0)
data_y.reset_index(drop=True, inplace=True)
data_X = pd.read_csv('data_X.csv', skiprows=lambda x: x % 500 != 0)
data_X.reset_index(drop=True, inplace=True)

data_X

,2_df,3_df,9_df,10_df,12_df,13_df,14_df,20_df,21_df,22_df,23_df,24_df,25_df
0,1.929622,0.714800,0.102610,3.204206,0.996662,67.028349,-0.868324,19.481377,2.241989e+00,0.437082,-2.804818,3.125796,83.774864
1,2.531229,0.758272,-0.386523,-0.781652,0.381195,5.168420,0.433815,14.442249,9.809170e+07,-0.209918,-3.362973,-0.896995,7.084704
2,1.082700,0.055614,0.314287,-0.765845,1.973787,1114.773248,-3.761644,10.327148,2.504404e+03,-0.977842,5.586231,-0.780689,23.726469
3,2.383469,0.616179,0.654736,0.957015,0.364150,993.496038,0.500670,-2.322874,2.362397e+03,-0.707074,3.823482,-0.125082,1.132835
4,1.093624,0.837940,-0.302161,-7.890309,0.227213,4.705690,-0.621454,0.096373,1.916541e+08,0.753711,11.141929,-0.859942,76.662840
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,1.052910,0.285095,0.181737,-3.013392,4.521296,0.001943,0.642006,17.372787,3.453134e+07,0.606385,-1.557221,-0.099218,45.489700
7996,1.754511,0.042470,0.404900,-0.189995,0.094286,0.003513,-0.279192,21.822714,7.399130e+04,0.297493,1.716022,0.520429,73.645010
7997,1.935684,0.725283,-0.832461,1.661456,-0.200040,19.200662,-7.494282,15.933747,4.774524e+03,0.554444,19.703510,-3.225583,108.782240
7998,1.008553,0.448947,0.984336,-1.323371,0.107204,198.310550,4.634744,-1.942958,2.567879e+04,-0.466803,13.801534,-0.987206,2.811831
7999,2.142622,0.703739,-0.134698,-0.639838,0.101540,18625.819597,0.344027,6.544363,3.490478e-01,-0.112118,2.995208,-0.380113,76.010110

In [86]:
data_y = data_y.drop(columns=['1_target'])
data_y_val = data_y_val.drop(columns=['1_target'])
data_y.values.ravel()
data_y

       0_target
0     1656.8312
1     3075.3523
2     2422.7130
3     3312.2688
4     3037.6995
...         ...
7995  2979.9058
7996  2041.8342
7997  3786.9067
7998  2884.3281
7999  2620.6970

[8000 rows x 1 columns]

### 1. Обучающая выборка данных разделена на обучающую и тестовую выборку

In [87]:

X_train, X_test, y_train, y_test = train_test_split(data_X, data_y, test_size=0.2, random_state=42)

### 2. Испытано как минимум три алгоритма разной сущности (RandomForest и XGBoost – разные сущности, а XGBoost и GradientBoosting – нет). Для оценки точности следует использовать тестовую выборку

In [88]:
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

from sklearn.metrics import accuracy_score

In [89]:
X_train.head()

,2_df,3_df,9_df,10_df,12_df,13_df,14_df,20_df,21_df,22_df,23_df,24_df,25_df
1467,1.825073,0.071326,-0.432592,2.321956,0.344640,83.223793,-3.026068,18.370052,1.557937e+07,0.136283,6.860083,-5.307323,71.934265
5768,1.130295,0.476373,0.239942,-1.540761,0.284984,0.042864,3.721120,7.663318,3.718237e+07,0.956252,9.355195,-0.202219,5.184694
5714,1.600759,0.664992,-0.446813,2.805620,0.761067,2257.848662,0.629989,21.384626,3.421493e-02,0.584524,14.160859,3.453231,97.361290
1578,1.241406,0.620579,0.149886,2.798643,0.238400,70.762269,0.312873,18.065178,3.147772e+03,0.719369,4.933547,-0.512382,22.164051
6958,1.359188,0.676775,-0.107695,1.707783,0.160479,256.824186,-0.184892,15.047076,5.055664e+05,0.330688,17.797379,-0.590065,56.324406

In [90]:
y_train.head(10)

       0_target
1467  4105.7856
5768  3999.2244
5714  2845.5808
1578  3841.2790
6958  4728.1387
6861  2341.8938
2126  5847.8916
6202  1376.0183
1450  1799.1550
5067  2195.5332

In [93]:

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Оценка качества модели
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

/home/c6/anaconda3/lib/python3.12/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Mean Squared Error: 202288.55039848125

In [99]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-2.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /home/c6/anaconda3/lib/python3.12/site-packages (from xgboost) (1.26.4)
Requirement already satisfied: nvidia-nccl-cu12 in /home/c6/anaconda3/lib/python3.12/site-packages (from xgboost) (2.21.5)
Requirement already satisfied: scipy in /home/c6/anaconda3/lib/python3.12/site-packages (from xgboost) (1.13.1)
Downloading xgboost-2.1.3-py3-none-manylinux_2_28_x86_64.whl (153.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.9/153.9 MB 10.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: xgboost
Successfully installed xgboost-2.1.3
Note: you may need to restart the kernel to use updated packages.

In [114]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression  # Линейная регрессия
from sklearn.tree import DecisionTreeRegressor     # Дерево решений
from xgboost import XGBRegressor                  # Градиентный бустинг
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [104]:
data_y

       0_target
0     1656.8312
1     3075.3523
2     2422.7130
3     3312.2688
4     3037.6995
...         ...
7995  2979.9058
7996  2041.8342
7997  3786.9067
7998  2884.3281
7999  2620.6970

[8000 rows x 1 columns]

In [105]:
import numpy as np
import pandas as pd

# Преобразуем data_y в одномерный массив
if isinstance(data_y, pd.DataFrame):  # Если data_y — DataFrame
    data_y = data_y.values.ravel()  # Преобразуем в массив NumPy и делаем его одномерным
elif isinstance(data_y, np.ndarray):  # Если data_y — массив NumPy
    if len(data_y.shape) > 1 and data_y.shape[1] == 1:  # Если форма (n_samples, 1)
        data_y = data_y.ravel()  # Преобразуем в одномерный массив
elif isinstance(data_y, list):  # Если data_y — список
    data_y = np.array(data_y).ravel()  # Преобразуем в массив NumPy и делаем его одномерным
else:
    raise ValueError("Unsupported data type for data_y. Please provide a 1D array-like object.")

# Теперь создаем Series
data_y = pd.Series(data_y)

# Разделим данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(data_X, data_y, test_size=0.2, random_state=42)

In [110]:
import time

## 3. Испытанные алгоритмы сравнены по точности, а также по скорости работы

In [111]:
# 1. Линейная регрессия
linear_model = LinearRegression()
start_train = time.time()
linear_model.fit(X_train, y_train)
end_train = time.time()
start_predict = time.time()
y_pred_linear = linear_model.predict(X_test)
end_predict = time.time()
mse_linear = mean_squared_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)
print(f"Linear Regression - MSE: {mse_linear:.4f}, R2: {r2_linear:.4f}")
print(f"Training time: {end_train - start_train:.4f} seconds")
print(f"Prediction time: {end_predict - start_predict:.4f} seconds\n")

Linear Regression - MSE: 796868.0384, R2: 0.4144
Training time: 0.0041 seconds
Prediction time: 0.0012 seconds

In [112]:
# 2. Дерево решений для регрессии
tree_model = DecisionTreeRegressor(random_state=42)
start_train = time.time()
tree_model.fit(X_train, y_train)
end_train = time.time()
start_predict = time.time()
y_pred_tree = tree_model.predict(X_test)
end_predict = time.time()
mse_tree = mean_squared_error(y_test, y_pred_tree)
r2_tree = r2_score(y_test, y_pred_tree)
print(f"Decision Tree - MSE: {mse_tree:.4f}, R2: {r2_tree:.4f}")
print(f"Training time: {end_train - start_train:.4f} seconds")
print(f"Prediction time: {end_predict - start_predict:.4f} seconds\n")

Decision Tree - MSE: 475537.5206, R2: 0.6505
Training time: 0.0851 seconds
Prediction time: 0.0012 seconds

In [113]:
# 3. Градиентный бустинг (XGBoost)
xgb_model = XGBRegressor(random_state=42)
start_train = time.time()
xgb_model.fit(X_train, y_train)
end_train = time.time()
start_predict = time.time()
y_pred_xgb = xgb_model.predict(X_test)
end_predict = time.time()
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
r2_xgb = r2_score(y_test, y_pred_xgb)
print(f"XGBoost - MSE: {mse_xgb:.4f}, R2: {r2_xgb:.4f}")
print(f"Training time: {end_train - start_train:.4f} seconds")
print(f"Prediction time: {end_predict - start_predict:.4f} seconds\n")

XGBoost - MSE: 172871.1019, R2: 0.8730
Training time: 0.2383 seconds
Prediction time: 0.0027 seconds

In [119]:

# Функция для вычисления метрик
def evaluate_model(y_true, y_pred):
    """
    Вычисляет R2 и RMSE для предсказаний модели.
    :param y_true: истинные значения
    :param y_pred: предсказанные значения
    :return: R2 и RMSE
    """
    r2 = r2_score(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    return r2, rmse

# Пример использования для трех моделей
metrics = []

# 1. Линейная регрессия
linear_model.fit(X_train, y_train)
y_pred_linear = linear_model.predict(X_test)
r2_linear, rmse_linear = evaluate_model(y_test, y_pred_linear)
metrics.append(('Linear Regression', r2_linear, rmse_linear))

# 2. Дерево решений
tree_model.fit(X_train, y_train)
y_pred_tree = tree_model.predict(X_test)
r2_tree, rmse_tree = evaluate_model(y_test, y_pred_tree)
metrics.append(('Decision Tree', r2_tree, rmse_tree))

# 3. Градиентный бустинг (XGBoost)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)
r2_xgb, rmse_xgb = evaluate_model(y_test, y_pred_xgb)
metrics.append(('XGBoost', r2_xgb, rmse_xgb))

# Вывод результатов
print(f"{'Model':<20} {'R2':<10} {'RMSE':<10}")
print("-" * 40)
for model_name, r2, rmse in metrics:
    print(f"{model_name:<20} {r2:<10.4f} {rmse:<10.4f}")

# Вычисление средних значений
average_r2 = np.mean([metric[1] for metric in metrics])
average_rmse = np.mean([metric[2] for metric in metrics])

print("\nAverage Metrics:")
print(f"Average R2: {average_r2:.4f}")
print(f"Average RMSE: {average_rmse:.4f}")

Model                R2         RMSE
----------------------------------------
Linear Regression    0.4144     892.6747
Decision Tree        0.6505     689.5923
XGBoost              0.8730     415.7777

Average Metrics:
Average R2: 0.6460
Average RMSE: 666.0149

In [118]:
def regression_accuracy(y_true, y_pred, tolerance=0.1):
    """
    Вычисляет точность для регрессии как долю предсказаний,
    которые находятся в пределах допустимой погрешности.
    :param y_true: истинные значения
    :param y_pred: предсказанные значения
    :param tolerance: допустимая относительная ошибка (например, 0.1 = 10%)
    :return: точность (accuracy)
    """
    errors = np.abs((y_pred - y_true) / y_true)
    accuracy = np.mean(errors <= tolerance)
    return accuracy

# Пример использования для трех моделей
metrics = []

# 1. Линейная регрессия
linear_model.fit(X_train, y_train)
y_pred_linear = linear_model.predict(X_test)
r2_linear, rmse_linear = evaluate_model(y_test, y_pred_linear)
accuracy_linear = regression_accuracy(y_test, y_pred_linear, tolerance=0.1)
metrics.append(('Linear Regression', r2_linear, rmse_linear, accuracy_linear))

# 2. Дерево решений
tree_model.fit(X_train, y_train)
y_pred_tree = tree_model.predict(X_test)
r2_tree, rmse_tree = evaluate_model(y_test, y_pred_tree)
accuracy_tree = regression_accuracy(y_test, y_pred_tree, tolerance=0.1)
metrics.append(('Decision Tree', r2_tree, rmse_tree, accuracy_tree))

# 3. Градиентный бустинг (XGBoost)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)
r2_xgb, rmse_xgb = evaluate_model(y_test, y_pred_xgb)
accuracy_xgb = regression_accuracy(y_test, y_pred_xgb, tolerance=0.1)
metrics.append(('XGBoost', r2_xgb, rmse_xgb, accuracy_xgb))

# Вывод результатов
print(f"{'Model':<20} {'R2':<10} {'RMSE':<10} {'Accuracy':<10}")
print("-" * 50)
for model_name, r2, rmse, accuracy in metrics:
    print(f"{model_name:<20} {r2:<10.4f} {rmse:<10.4f} {accuracy:<10.4f}")

# Вычисление средних значений
average_r2 = np.mean([metric[1] for metric in metrics])
average_rmse = np.mean([metric[2] for metric in metrics])
average_accuracy = np.mean([metric[3] for metric in metrics])

print("\nAverage Metrics:")
print(f"Average R2: {average_r2:.4f}")
print(f"Average RMSE: {average_rmse:.4f}")
print(f"Average Accuracy: {average_accuracy:.4f}")

Model                R2         RMSE       Accuracy
--------------------------------------------------
Linear Regression    0.4144     892.6747   0.2400
Decision Tree        0.6505     689.5923   0.3162
XGBoost              0.8730     415.7777   0.4831

Average Metrics:
Average R2: 0.6460
Average RMSE: 666.0149
Average Accuracy: 0.3465

In [121]:
from sklearn.preprocessing import LabelEncoder

In [126]:
# Функция для нормализации столбцов DataFrame
def normalize_dataframe(df, columns=None):
    """
    Нормализует значения в указанных столбцах DataFrame в диапазон [0, 1].
    
    :param df: pandas DataFrame
    :param columns: Список столбцов для нормализации. Если None, нормализуются все числовые столбцы.
    :return: DataFrame с нормализованными значениями
    """
    df_normalized = df.copy()  # Создаем копию DataFrame, чтобы не изменять исходный
    if columns is None:
        # Если список столбцов не указан, выбираем все числовые столбцы
        columns = df.select_dtypes(include=['number']).columns
    
    for col in columns:
        df_normalized[col] = (df[col] - df[col].min()) / (df[col].max() - df[col].min())
    
    return df_normalized

In [133]:
data_y_val = pd.read_csv('data_y_val.csv', skiprows=lambda x: x % 500 != 0)
data_y_val.reset_index(drop=True, inplace=True)
data_X_val = pd.read_csv('data_X_val.csv', skiprows=lambda x: x % 500 != 0)
data_X_val.reset_index(drop=True, inplace=True)
data_y = pd.read_csv('data_y.csv', skiprows=lambda x: x % 500 != 0)
data_y.reset_index(drop=True, inplace=True)
data_X = pd.read_csv('data_X.csv', skiprows=lambda x: x % 500 != 0)
data_X.reset_index(drop=True, inplace=True)

In [134]:
data_y = data_y.drop(columns=['1_target'])
data_y_val = data_y_val.drop(columns=['1_target'])

In [142]:
X_train, X_test, y_train, y_test = train_test_split(data_X, data_y, test_size=0.2, random_state=42)

In [143]:
y_train = normalize_dataframe(y_train)

In [144]:
y_train

      0_target
1467  0.675279
5768  0.662355
5714  0.522439
1578  0.643199
6958  0.750759
...        ...
5226  0.284950
5390  0.492636
860   0.519040
7603  0.469368
7270  0.590411

[6400 rows x 1 columns]

In [145]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Предполагаем, что data_y содержит метки классов
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)

/home/c6/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [146]:
y_train

array([5539, 5410, 3338, ..., 3289, 2444, 4468])

In [148]:
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Начинаем отсчет времени
start_time = time.time()

# Создаем и обучаем классификатор
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

# Делаем предсказания
y_pred = classifier.predict(X_test)

# Вычисляем accuracy_score
#accuracy = accuracy_score(y_test, y_pred)

# Заканчиваем отсчет времени
end_time = time.time()
execution_time = end_time - start_time

# Выводим результаты
#print(f"Accuracy (Logistic Regression): {accuracy:.4f}")
print(f"Execution Time: {execution_time:.4f} seconds")

Execution Time: 225.5608 seconds

/home/c6/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Начинаем отсчет времени
start_time = time.time()

# Создаем и обучаем классификатор Random Forest
classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, y_train)

# Делаем предсказания
y_pred = classifier.predict(X_test)

# Вычисляем accuracy_score
accuracy = accuracy_score(y_test, y_pred)

# Заканчиваем отсчет времени
end_time = time.time()
execution_time = end_time - start_time

# Выводим результаты
print(f"Accuracy (Random Forest): {accuracy:.4f}")
print(f"Execution Time: {execution_time:.4f} seconds")

### 4. Лучший алгоритм реализован в виде пайплайна, принимающего на вход пути к файлам, а на выходе возвращает обученную модель, а также метрики модели на валидационной выборке в виде словаря (необходимые метрики: средний коэффициент детерминации R2 и средний RMSE).

# ВОт Пайплайн

In [4]:
def normalize_dataframe(data_y_val,data_X_val,data_y,data_X):
    def regression_accuracy(y_true, y_pred, tolerance=0.1):
        """
        Вычисляет точность для регрессии как долю предсказаний,
        которые находятся в пределах допустимой погрешности.
        :param y_true: истинные значения
        :param y_pred: предсказанные значения
        :param tolerance: допустимая относительная ошибка (например, 0.1 = 10%)
        :return: точность (accuracy)
        """
        errors = np.abs((y_pred - y_true) / y_true)
        accuracy = np.mean(errors <= tolerance)
        return accuracy

    data_y_val = pd.read_csv('data_y_val.csv', skiprows=lambda x: x % 500 != 0)
    data_y_val.reset_index(drop=True, inplace=True)
    data_X_val = pd.read_csv('data_X_val.csv', skiprows=lambda x: x % 500 != 0)
    data_X_val.reset_index(drop=True, inplace=True)
    data_y = pd.read_csv('data_y.csv', skiprows=lambda x: x % 500 != 0)
    data_y.reset_index(drop=True, inplace=True)
    data_X = pd.read_csv('data_X.csv', skiprows=lambda x: x % 500 != 0)
    data_X.reset_index(drop=True, inplace=True)

    data_y = data_y.drop(columns=['1_target'])
    data_y_val = data_y_val.drop(columns=['1_target'])
    data_y.values.ravel()
    
    X_train, X_test, y_train, y_test = train_test_split(data_X, data_y, test_size=0.2, random_state=42)

    # XGBoos
    xgb_model = XGBRegressor(random_state=42)
    start_train = time.time()
    xgb_model.fit(X_train, y_train)
    end_train = time.time()
    start_predict = time.time()
    y_pred_xgb = xgb_model.predict(X_test)
    end_predict = time.time()
    mse_xgb = mean_squared_error(y_test, y_pred_xgb)
    r2_xgb = r2_score(y_test, y_pred_xgb)
    print(f"XGBoost - MSE: {mse_xgb:.4f}, R2: {r2_xgb:.4f}")
    print(f"Training time: {end_train - start_train:.4f} seconds")
    print(f"Prediction time: {end_predict - start_predict:.4f} seconds\n")
    
    # ВОТ СДЕСЬ Я ЗАПИСЫВАЮ МЕТРИКИ В ФАЙЛИК metrics.txt
    metrics = []
    accuracy_xgb = regression_accuracy(y_test, y_pred_xgb, tolerance=0.1)
    metrics.append(('XGBoost', r2_xgb, rmse_xgb, accuracy_xgb))

    # Prepare the output string
    output_lines = []
    output_lines.append(f"{'Model':<20} {'R2':<10} {'RMSE':<10} {'Accuracy':<10}")
    output_lines.append("-" * 50)

    for model_name, r2, rmse, accuracy in metrics:
        output_lines.append(f"{model_name:<20} {r2:<10.4f} {rmse:<10.4f} {accuracy:<10.4f}")

    # Write the results to metrics.txt
    with open('metrics.txt', 'w') as f:
        for line in output_lines:
            f.write(line + '\n')
    # Вычисление средних значений
    average_r2 = np.mean([metric[1] for metric in metrics])
    average_rmse = np.mean([metric[2] for metric in metrics])
    average_accuracy = np.mean([metric[3] for metric in metrics])

    print("\nAverage Metrics:")
    print(f"Average R2: {average_r2:.4f}")
    print(f"Average RMSE: {average_rmse:.4f}")
    print(f"Average Accuracy: {average_accuracy:.4f}")

    return xgb_model